export enum IRoute {
  HOME = '/',
  SUBJECT_LIST = '/danh-sach-mon-hoc',
  CHANGE_PASSWORD = '/doi-mat-khau',
  FORGOT_PASSWORD = '/quen-mat-khau',
  EMAIL_SENT = '/emailSent/:userEmail/:reset?',
  RESET_PASSWORD = '/dat-lai-mat-khau',
  HISTORY = '/lich-su-thi',
  LOGOUT = '/dang-xuat',
  CREATE_EXAM = '/tao-de-thi',
  ADD_SUBJECT = '/them-mon-thi',
  CLASS_LIST = '/danh-sach-lop',
  STUDENT_LIST = '/danh-sach-sinh-vien',
  TEST = '/test',
}
